//! Decode a small reference JPEG generated by ffmpeg.

use std::path::Path;
use std::process::Command;

use oxideav_core::{CodecId, CodecParameters, Frame, Packet, PixelFormat, TimeBase};

fn generate_red_jpeg(path: &Path) -> bool {
    let status = Command::new("/usr/bin/ffmpeg")
        .args([
            "-y",
            "-loglevel",
            "quiet",
            "-f",
            "lavfi",
            "-i",
            "color=c=red:s=64x64:d=1",
            "-frames:v",
            "1",
            "-update",
            "1",
        ])
        .arg(path)
        .status();
    matches!(status, Ok(s) if s.success())
}

#[test]
fn decode_ffmpeg_red_jpeg() {
    let path = std::env::temp_dir().join("oxideav_mjpeg_test_red.jpg");
    if !generate_red_jpeg(&path) {
        eprintln!("ffmpeg not available — skipping");
        return;
    }
    let bytes = std::fs::read(&path).expect("read jpeg");

    let mut params = CodecParameters::video(CodecId::new("mjpeg"));
    params.width = Some(64);
    params.height = Some(64);
    let mut dec = oxideav_mjpeg::decoder::make_decoder(&params).expect("make decoder");

    let pkt = Packet::new(0, TimeBase::new(1, 90_000), bytes);
    dec.send_packet(&pkt).expect("send");
    let frame = dec.receive_frame().expect("decode");
    let Frame::Video(v) = frame else {
        panic!("expected video frame");
    };

    assert_eq!(v.width, 64);
    assert_eq!(v.height, 64);
    assert_eq!(v.format, PixelFormat::Yuv420P);

    let y_mean: u64 =
        v.planes[0].data.iter().map(|&b| b as u64).sum::<u64>() / v.planes[0].data.len() as u64;
    let cb_mean: u64 =
        v.planes[1].data.iter().map(|&b| b as u64).sum::<u64>() / v.planes[1].data.len() as u64;
    let cr_mean: u64 =
        v.planes[2].data.iter().map(|&b| b as u64).sum::<u64>() / v.planes[2].data.len() as u64;
    eprintln!("red jpeg means: Y={y_mean} Cb={cb_mean} Cr={cr_mean}");

    // BT.601 red: Y≈76, Cb≈85, Cr≈255. Allow decode tolerance.
    assert!(
        (y_mean as i64 - 76).abs() < 10,
        "luma mean = {y_mean}, want ≈76"
    );
    assert!(
        (cb_mean as i64 - 85).abs() < 15,
        "Cb mean = {cb_mean}, want ≈85"
    );
    assert!(
        (cr_mean as i64 - 255).abs() < 20,
        "Cr mean = {cr_mean}, want ≈255"
    );
}

/// Reject a progressive (SOF2) JPEG with Error::Unsupported.
#[test]
fn reject_progressive_jpeg() {
    let path = std::env::temp_dir().join("oxideav_mjpeg_test_prog.jpg");
    let status = Command::new("/usr/bin/ffmpeg")
        .args([
            "-y",
            "-loglevel",
            "quiet",
            "-f",
            "lavfi",
            "-i",
            "color=c=green:s=64x64:d=1",
            "-frames:v",
            "1",
            "-update",
            "1",
            "-vf",
            "format=yuvj420p",
            "-mjpeg_huffman_tables",
            "0",
        ])
        .arg("-huffman")
        .arg("0")
        .arg("-progressive")
        .arg("1")
        .arg(&path)
        .status();
    let _ = status; // ignore; some ffmpeg builds lack the flag.
                    // Alternate strategy: try jpegtran if available. If neither method succeeds, skip.
    if !path.exists() {
        // Fallback: synthesise the SOF2 case by hand.
        // JPEG header fragments: SOI + minimal APP0 + SOF2 marker → reader should
        // reject.
        let minimal = vec![
            0xFF, 0xD8, // SOI
            0xFF, 0xE0, 0x00, 0x10, b'J', b'F', b'I', b'F', 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0xFF,
            0xC2, // SOF2 (progressive)
            0x00, 0x11, // length
            0x08, 0x00, 0x40, 0x00, 0x40, 0x03, 0x01, 0x22, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11,
            0x01,
        ];
        let mut params = CodecParameters::video(CodecId::new("mjpeg"));
        let mut dec = oxideav_mjpeg::decoder::make_decoder(&params.clone()).unwrap();
        params.width = Some(64);
        params.height = Some(64);
        let pkt = Packet::new(0, TimeBase::new(1, 90_000), minimal);
        dec.send_packet(&pkt).unwrap();
        let err = dec.receive_frame().expect_err("should fail");
        let msg = err.to_string();
        assert!(
            msg.contains("progressive"),
            "expected 'progressive' in error, got: {msg}"
        );
        return;
    }
    // If the file exists and is progressive, confirm rejection.
    let bytes = std::fs::read(&path).unwrap();
    if bytes.len() < 10 {
        return;
    }
    // Quick signature check for SOF2 (0xFFC2); skip otherwise.
    let has_sof2 = bytes.windows(2).any(|w| w == [0xFF, 0xC2]);
    if !has_sof2 {
        return;
    }
    let mut params = CodecParameters::video(CodecId::new("mjpeg"));
    params.width = Some(64);
    params.height = Some(64);
    let mut dec = oxideav_mjpeg::decoder::make_decoder(&params).unwrap();
    let pkt = Packet::new(0, TimeBase::new(1, 90_000), bytes);
    dec.send_packet(&pkt).unwrap();
    let err = dec.receive_frame().expect_err("should reject");
    assert!(err.to_string().contains("progressive"));
}
